# $Id: Makefile 484 2005-06-28 15:56:35Z witchel $

.SUFFIXES: .fig .dvi .ps

VERSION = NoVersionGiven

all: pdf 

#----------------------------------------------------------------------
# Source files.  Edit these variables for each new paper.
#----------------------------------------------------------------------

name = research

latex_files = $(name).tex \
		psfig_macros.tex \
		bibliography.bib

# Xfig source.
xfig_files = 	

# EPS generated by xfig.  Don't strictly need this to rebuild paper,
# but don't want to clean it.
xfig_eps_files = 	

# EPS files generated somewhere else, i.e., no other way of generating
# them locally.
eps_files =

#----------------------------------------------------------------------
# Framemaker figures.

fm_figs = 

# Postscript generated from framemaker figures.
fm_eps = 

#----------------------------------------------------------------------
# Other valuable files, but which are not needed to generate document
#----------------------------------------------------------------------

misc_files = 

# Stuff not used now, but potentially reusable.
unused_files =	

#----------------------------------------------------------------------
# Shouldn't have to touch anything below here...
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# LaTeX commands.
#----------------------------------------------------------------------

dvi: $(fm_eps)
	rubber -Wrefs -Wmisc $(name)

latex_junk = 	$(name).dvi \
		*.aux \
		$(name).log \
		$(name).blg \
		$(name).brf \
		$(name).bbl \
		$(name).toc \
		psfig.aux

#----------------------------------------------------------------------
# Postscript/PDF generation.
#----------------------------------------------------------------------

pdf: $(name).pdf 
ps: $(name).ps

# DISTILL = distill
# DISTILL_FLAGS = -embedallfonts on -maxsubsetpct 100

#DISTILL = ps2pdf
#DISTILL_FLAGS = -dPDFSETTINGS=/prepress -dEmbedAllFonts=true 

$(name).pdf: *.tex $(fm_eps) bibliography.bib 
	rubber -Wrefs -Wmisc -d $(name)

#	./check_pdf_embedded_fonts.sh $(name).pdf
# the following option does not show hyperref info correctly
# ps2pdf -sPAPERSIZE=letter -dPDFSETTINGS=/prepress -dEmbedAllFonts=true \
# 	$(name).ps $(name).pdf

$(name).ps: *.tex $(fm_eps) bibliography.bib 
	rubber -Wrefs -Wmisc -p $(name)

#	$(DISTILL) $(DISTILL_FLAGS) $(name).ps




ps_junk =  $(name).pdf

#----------------------------------------------------------------------
# HTML generation.
#----------------------------------------------------------------------

LATEX2HTML = hevea
LATEX2HTML_FLAGS = hevea-compat.hva 

html: $(name).ps
	$(LATEX2HTML) $(LATEX2HTML_FLAGS) $(name).tex
	imagen $(name)

#----------------------------------------------------------------------
# Document previewers.
#----------------------------------------------------------------------

x:
	xdvi -s 5 $(name) &

gv: $(name).ps
	gv $(name).ps &

#----------------------------------------------------------------------
# Group related files.
#----------------------------------------------------------------------

# Precious files.
rcs_files = 	$(latex_files) \
		$(eps_files) \
		$(xfig_files) \
		$(fm_figs)\
		$(misc_files) \
		$(unused_files) \
		Makefile

# Garbage files.
junk = $(latex_junk) $(ps_junk)

#----------------------------------------------------------------------
# RCS stuff.
#----------------------------------------------------------------------

ensure-ci:
	@if [ `rlog -L -l -R $(rcs_files) | wc -w` -ne 0 ]; \
    then \
        echo "ERROR: The following files are not checked in:"; \
        rlog -L -l -R $(rcs_files); \
        exit 1; \
    fi

version : ensure-ci
	rcs "-n$(VERSION):" $(rcs_files)

rm-version:
	rcs "-n$(VERSION)" $(rcs_files)

#----------------------------------------------------------------------
# Backup paranoia.
#----------------------------------------------------------------------

# Creates tar file in parent directory.
tar:	ensure-ci
	(cd ..; tar cvf eeregfile.tar eeregfile)

#----------------------------------------------------------------------
# Miscellaneous.
#----------------------------------------------------------------------

open:
	gnome-open $(name).pdf

tags:
	etags $(latex_files)

clean:
	rm -f $(junk) $(name).pdf $(name).ps $(name).dvi

count:
	wc $(latex_files)
